version: '3.9'

services:
  app_prod:
    build:
      context: https://github.com/nunsez/docker-nginx-proxy.git#master
      dockerfile: services/prod/Dockerfile.prod
      args:
        - BUNDLER_VERSION=2.1.4

  app_dev:
    build:
      context: https://github.com/nunsez/docker-nginx-proxy.git#dev
      dockerfile: services/dev/Dockerfile.dev
      args:
        - BUNDLER_VERSION=2.1.4
    volumes:
      - bundle_cache:/usr/local/bundle

  nginx:
    build:
      context: https://github.com/nunsez/docker-nginx-proxy.git#master
      dockerfile: services/nginx/Dockerfile
    ports:
      - 6666:7777
      - 8888:9999
    links:
      - app_dev
      - app_prod

volumes:
  bundle_cache:
    driver: local
