version: '3.9'

services:
  app_prod:
    build:
      context: https://github.com/nunsez/docker-nginx-proxy.git#master
      dockerfile: services/prod/Dockerfile.prod
      args:
        - BUNDLER_VERSION=2.1.4
    command: bundle exec rails server -b 0.0.0.0
    environment:
      - RAILS_ENV=development
    networks:
      - nginx
    depends_on:
      - nginx

  app_dev:
    build:
      context: https://github.com/nunsez/docker-nginx-proxy.git#dev
      dockerfile: services/dev/Dockerfile.dev
      args:
        - BUNDLER_VERSION=2.1.4
    command: bundle exec rails server -b 0.0.0.0
    environment:
      - RAILS_ENV=development
    networks:
      - nginx
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      # context: https://github.com/nunsez/docker-nginx-proxy.git#master
      dockerfile: services/nginx/Dockerfile
    ports:
      - 4000:4000
      - 5000:5000

networks:
  nginx:
