FROM ruby:2.4.1-slim

ENV LANG=en_US.UTF-8

RUN apt-get update && apt-get install --yes \
    curl \
    file \
    g++ \
    gcc \
    git \
    make \
    openssl \
    pkg-config \
    tzdata

ARG BUNDLER_VERSION
ENV BUNDLER_VERSION=${BUNDLER_VERSION}

RUN gem install bundler --version "${BUNDLER_VERSION}"

ENV APP_PATH="/app"
WORKDIR ${APP_PATH}

COPY . .
